title: Jinghan Xu
description: Portfolio
url: "https://jhanxxx.github.io"
baseurl: ""
lang: en
timezone: Europe/Stockholm
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
author:
  name: Jinghan Xu
  email: jinghanx@kth.se
  github: https://github.com/JhanXXX
  scholar: https://scholar.google.com/citations?user=TMB0z1oAAAAJ
  linkedin: https://www.linkedin.com/in/jinghan-xu-8129b0309/
defaults:
  - scope:
      path: ""
    values:
      layout: default
exclude:
  - backups
  - steam remarks
  - scripts
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
  - .bundle
  - requirements-preview.txt
  - CHECKS.md
